### ISSUE TITLE
Javascript heap out of memory when running dsweeper

### ISSUE THREAD

**Issue by ziritrion** [simsalabim/dsweeper#9]
Hello;

I'm running Dropbox on an external Samsung SSD (exfat) from my macbook pro running High Sierra. I'm a Dropbox Business User and my Dropbox folder is over 700GB in size.

Running the daemonized dsweeper wasn't working, so I tried to run it normally. I got the error posted below. I'd appreciate any help.

Dropbox AppleDouble sweeper is running.

<--- Last few GCs --->

[907:0x104801400]   268141 ms: Mark-sweep 1395.1 (1457.4) -> 1395.1 (1457.9) MB, 1430.1 / 18.8 ms  allocation failure GC in old space requested
[907:0x104801400]   269588 ms: Mark-sweep 1395.1 (1457.9) -> 1395.1 (1426.9) MB, 1447.6 / 17.5 ms  last resort GC in old space requested
[907:0x104801400]   270990 ms: Mark-sweep 1395.1 (1426.9) -> 1395.1 (1426.9) MB, 1401.3 / 17.5 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1d14b2825501 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [/usr/local/lib/node_modules/dsweeper/lib/file_finder.js:~29] [pc=0x2efb2c99ddb](this=0x1d14860822d1 <undefined>,subdir=0x1d14a7c8f4e9 <String[139]: /Volumes/Samsung_T5/Dropbox/master/Descargas/05 - Business Modelling/SalesQuoteDemo/ApproveDealUI/public_html/WEB-INF/temp/adf/styles/cache>)
    2: arguments adaptor frame: 3->1
    3: forEach(this=0x1d14...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [/usr/local/bin/node]
 7: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::EnsureCapacity(v8::internal::Handle<v8::internal::NameDictionary>, int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 8: v8::internal::Dictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::Add(v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, int*) [/usr/local/bin/node]
 9: v8::internal::LookupIterator::ApplyTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>) [/usr/local/bin/node]
10: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
11: v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [/usr/local/bin/node]
12: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x2efb2b042fd
14: 0x2efb2c99ddb
[1]    907 abort      dsweeper

**Comment by simsalabim** [comment]
Hi. I think this is the [answer](https://stackoverflow.com/a/38560292). Try increasing memory size with `NODE_OPTIONS="--max-old-space-size=4096" dsweeper`. NODE_OPTIONS works for me with node v8.6.0 but I heard there were some issues with it in one of the 6x.

Please let me know if it fixed the error.
